# Generated by Django 4.2.7 on 2024-02-11 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='City',
            new_name='city',
        ),
    ]
