# Generated by Django 4.2.7 on 2024-03-03 13:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0009_lesson_price_trainingcourse_price'),
        ('users', '0004_alter_payments_paid_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='url_for_payment',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка для оплаты'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='date_payment',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата оплаты'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='paid_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.trainingcourse', verbose_name='Оплаченный курс'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='paid_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.lesson', verbose_name='Оплаченный урок'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_amount',
            field=models.IntegerField(verbose_name='Сумма оплаты'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'наличными'), ('card', 'картой')], max_length=35, verbose_name='Способ оплаты'),
        ),
    ]
