# Generated by Django 4.2.7 on 2024-03-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_payments_url_for_payment_alter_payments_date_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='payment_id',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='id сессии оплаты'),
        ),
    ]
