# Generated by Django 4.2.7 on 2024-03-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_payments_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сумма оплаты'),
        ),
    ]
