# Generated by Django 4.2.7 on 2024-03-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_payments_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='product_stripe_id',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='id продукта stripe'),
        ),
    ]
