# Generated by Django 4.2.7 on 2024-03-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0009_lesson_price_trainingcourse_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcourse',
            name='last_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='последнее обновление'),
        ),
    ]
